<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:connectorconfiguration="http://www.bonitasoft.org/model/connector/configuration" xmlns:decision="http://www.bonitasoft.org/ns/bpm/process/decision" xmlns:definition="http://www.bonitasoft.org/ns/connector/definition/6.1" xmlns:expression="http://www.bonitasoft.org/ns/bpm/expression" xmlns:notation="http://www.eclipse.org/gmf/runtime/1.0.3/notation" xmlns:process="http://www.bonitasoft.org/ns/bpm/process">
  <process:MainProcess xmi:id="_qnjxUKKMEfGM4bfaUYLK2A" name="Diagram" bonitaModelVersion="9">
    <elements xmi:type="process:Pool" xmi:id="_qnkYYKKMEfGM4bfaUYLK2A" name="Plataforma RescueSync" displayName="Plataforma RescueSync">
      <elements xmi:type="process:Lane" xmi:id="_qnkYYaKMEfGM4bfaUYLK2A" name="Operador Municipal" actor="_POFZQKZyEfG__aNESQ6L_g">
        <elements xmi:type="process:StartEvent" xmi:id="_qnkYYqKMEfGM4bfaUYLK2A" name="Inicio de emergencia" outgoing="_qnkYd6KMEfGM4bfaUYLK2A">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_qnkYY6KMEfGM4bfaUYLK2A" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_qnkYZKKMEfGM4bfaUYLK2A" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_qnkYZaKMEfGM4bfaUYLK2A" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_jWws0KZ0EfG__aNESQ6L_g" documentation="Esta tarea consulta las ofertas previamente validadas por el Sistema Nacional para evaluar su adecuación a las necesidades de la emergencia." name="Visualizar ofertas validadas" outgoing="_cNlO8KcJEfGqR_1kgwv4Ug" incoming="_Wwiz4KyuEfGhNt0l83QQlQ" actor="_POFZQKZyEfG__aNESQ6L_g" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_jWyiAaZ0EfG__aNESQ6L_g" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_jWyiAKZ0EfG__aNESQ6L_g" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_jWyiAqZ0EfG__aNESQ6L_g" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_jWyiA6Z0EfG__aNESQ6L_g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_jWyiBKZ0EfG__aNESQ6L_g" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_jWyiBaZ0EfG__aNESQ6L_g" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_jWyiB6Z0EfG__aNESQ6L_g" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_jWyiBqZ0EfG__aNESQ6L_g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_jWyiCaZ0EfG__aNESQ6L_g" type="NONE">
            <targetForm xmi:type="expression:Expression" xmi:id="_zuADYLLdEfGMcrvc5IFQ8w" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_jWyiCKZ0EfG__aNESQ6L_g"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_jWyiC6Z0EfG__aNESQ6L_g" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_baFVcKcJEfGqR_1kgwv4Ug" documentation="Esta tarea selecciona y adjudica la oferta validada que mejor cubra las necesidades identificadas para la emergencia en curso, ademas notifica la adjudicacion de la oferta a la ONG correspondiente." name="Adjudicar y notificar oferta a ONG" outgoing="_O61jMK1vEfGkRvrEd11-kw" incoming="_cNlO8KcJEfGqR_1kgwv4Ug" actor="_POFZQKZyEfG__aNESQ6L_g" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_baQUkKcJEfGqR_1kgwv4Ug" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_baPtgKcJEfGqR_1kgwv4Ug" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_baQUkacJEfGqR_1kgwv4Ug" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_baQUkqcJEfGqR_1kgwv4Ug" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_baQUk6cJEfGqR_1kgwv4Ug" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_baQUlKcJEfGqR_1kgwv4Ug" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_baQUlqcJEfGqR_1kgwv4Ug" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_baQUlacJEfGqR_1kgwv4Ug" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_baQUmKcJEfGqR_1kgwv4Ug" type="NONE">
            <targetForm xmi:type="expression:Expression" xmi:id="_zuADYbLdEfGMcrvc5IFQ8w" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_baQUl6cJEfGqR_1kgwv4Ug"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_baQUmqcJEfGqR_1kgwv4Ug" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_2A2OEKyuEfGhNt0l83QQlQ" documentation="Esta tarea registra una emergencia en el sistema, detallando el nivel de gravedad, la zona afectada y una descripción inicial. " name="Registrar  emergencia" outgoing="_MCOh8KysEfGhNt0l83QQlQ" incoming="_qnkYd6KMEfGM4bfaUYLK2A" actor="_POFZQKZyEfG__aNESQ6L_g" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_qnkYZ6KMEfGM4bfaUYLK2A" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_qnkYaKKMEfGM4bfaUYLK2A" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_qnkYaaKMEfGM4bfaUYLK2A" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_qnkYaqKMEfGM4bfaUYLK2A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_qnkYa6KMEfGM4bfaUYLK2A" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_qnkYbKKMEfGM4bfaUYLK2A" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_qnkYbaKMEfGM4bfaUYLK2A" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_qnkYbqKMEfGM4bfaUYLK2A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_2A21KayuEfGhNt0l83QQlQ" type="NONE">
            <targetForm xmi:type="expression:Expression" xmi:id="_JMtB0LL4EfGMcrvc5IFQ8w" name="registrarEmergencia" content="4d3e40ec-b8c4-4b0d-8460-40cdad13b319" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_2A21KKyuEfGhNt0l83QQlQ"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_2A21K6yuEfGhNt0l83QQlQ" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
      </elements>
      <elements xmi:type="process:Lane" xmi:id="_IFdV8KLeEfG0-Lqmhfo29w" name="Centro Coordinador" actor="_wvye8KpPEfGoZ6gUKq0Gdw">
        <elements xmi:type="process:Task" xmi:id="_2qWY4KpPEfGoZ6gUKq0Gdw" documentation="Esta tarea desglosa y cuantifica las necesidades en &quot;Lotes de Necesidades&quot;(ej: 5 Paramédicos, 1000 raciones de&#xA;alimento)" name="Generar lotes de necesidades" outgoing="_Aa4e0KpQEfGoZ6gUKq0Gdw" incoming="_MCOh8KysEfGhNt0l83QQlQ" actor="_wvye8KpPEfGoZ6gUKq0Gdw" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_2qWY4apPEfGoZ6gUKq0Gdw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_2qWY4qpPEfGoZ6gUKq0Gdw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_2qWY46pPEfGoZ6gUKq0Gdw" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_2qWY5KpPEfGoZ6gUKq0Gdw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_2qWY5apPEfGoZ6gUKq0Gdw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_2qWY5qpPEfGoZ6gUKq0Gdw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_2qWY56pPEfGoZ6gUKq0Gdw" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_2qWY6KpPEfGoZ6gUKq0Gdw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_2qWY6apPEfGoZ6gUKq0Gdw" type="NONE">
            <targetForm xmi:type="expression:Expression" xmi:id="_zuADYrLdEfGMcrvc5IFQ8w" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_2qWY66pPEfGoZ6gUKq0Gdw"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_2qWY7KpPEfGoZ6gUKq0Gdw" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_GSPaIKpYEfGoZ6gUKq0Gdw" documentation="Esta tarea publica oficialmente la convocatoria a toda la red" name="Publicar convocatoria a toda la red" outgoing="_BYtZAKpQEfGoZ6gUKq0Gdw" incoming="_Aa4e0KpQEfGoZ6gUKq0Gdw _vE_ocK1tEfGkRvrEd11-kw">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_-Om0gapPEfGoZ6gUKq0Gdw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_-Om0gqpPEfGoZ6gUKq0Gdw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_-Om0g6pPEfGoZ6gUKq0Gdw" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_-Om0hKpPEfGoZ6gUKq0Gdw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_-Om0hapPEfGoZ6gUKq0Gdw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_-Om0hqpPEfGoZ6gUKq0Gdw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_-Om0h6pPEfGoZ6gUKq0Gdw" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_-Om0iKpPEfGoZ6gUKq0Gdw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_dJ_bsKpdEfGoZ6gUKq0Gdw" documentation="Esta tarea monitorea y comunica al sistema centralizado el estado de finalización de las actividades de las distintas ONGs mediante la API Cloud." name="Monitorear la ejecucion" outgoing="_gUoOsKytEfGhNt0l83QQlQ" incoming="_fauyQKytEfGhNt0l83QQlQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_dJ_bsapdEfGoZ6gUKq0Gdw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_dJ_bsqpdEfGoZ6gUKq0Gdw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_dJ_bs6pdEfGoZ6gUKq0Gdw" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_dJ_btKpdEfGoZ6gUKq0Gdw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_dJ_btapdEfGoZ6gUKq0Gdw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_dJ_btqpdEfGoZ6gUKq0Gdw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_dJ_bt6pdEfGoZ6gUKq0Gdw" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_dJ_buKpdEfGoZ6gUKq0Gdw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_ZIRqgK4SEfG95paOjq0xJQ" documentation="Esta tarea evalua que acciones tomar de acuerdo a lo que decida el centro coordinador encargado de la emergencia." name="Evaluar acciones a tomar" outgoing="_vE_ocK1tEfGkRvrEd11-kw" incoming="_UaVKcKyuEfGhNt0l83QQlQ" actor="_wvye8KpPEfGoZ6gUKq0Gdw" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_rWU-Ua1tEfGkRvrEd11-kw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_rWU-UK1tEfGkRvrEd11-kw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_rWVlYK1tEfGkRvrEd11-kw" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_rWVlYa1tEfGkRvrEd11-kw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_rWVlYq1tEfGkRvrEd11-kw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_rWVlY61tEfGkRvrEd11-kw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_rWVlZa1tEfGkRvrEd11-kw" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_rWVlZK1tEfGkRvrEd11-kw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_ZIj-Ya4SEfG95paOjq0xJQ" type="NONE">
            <targetForm xmi:type="expression:Expression" xmi:id="_zuADY7LdEfGMcrvc5IFQ8w" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_ZIj-YK4SEfG95paOjq0xJQ"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_ZIj-Y64SEfG95paOjq0xJQ" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
      </elements>
      <elements xmi:type="process:Lane" xmi:id="_VASqUKMCEfGpRZzXDYFkZQ" name="Representante ONG" actor="_mnwDgKfUEfG0OL1MHS4NJA">
        <elements xmi:type="process:Task" xmi:id="_3PAw8Kc1EfGSnoVaS4_jWA" documentation="Esta tarea permite cargar ofertas dentro de una ventana de tiempo estipulada por la urgencia" name="Cargar ofertas de  ayuda" incoming="_BYtZAKpQEfGoZ6gUKq0Gdw" actor="_mnwDgKfUEfG0OL1MHS4NJA" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_3P_BUac1EfGSnoVaS4_jWA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_3P_BUKc1EfGSnoVaS4_jWA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_3P_BUqc1EfGSnoVaS4_jWA" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_3P_BU6c1EfGSnoVaS4_jWA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_3P_BVKc1EfGSnoVaS4_jWA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_3P_BVac1EfGSnoVaS4_jWA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_3P_BV6c1EfGSnoVaS4_jWA" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_3P_BVqc1EfGSnoVaS4_jWA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <BoundaryIntermediateEvents xmi:type="process:BoundaryTimerEvent" xmi:id="_oNl7ILu4EfGcCZX-Fsupjg" name="Ventana de tiempo" outgoing="_ps1gULu4EfGcCZX-Fsupjg">
            <condition xmi:type="expression:Expression" xmi:id="_sKIpMLu4EfGcCZX-Fsupjg" name="ventana_tiempo_ms" content="ventana_tiempo_ms" type="TYPE_VARIABLE" returnType="java.lang.Long">
              <referencedElements xmi:type="process:Data" xmi:id="_t0RPwLu4EfGcCZX-Fsupjg" documentation="Tiempo máximo de espera, expresado en milisegundos, antes de que la tarea finalice automáticamente o continúe por el flujo definido en el temporizador." name="ventana_tiempo_ms" dataType="_qnkYjqKMEfGM4bfaUYLK2A"/>
            </condition>
          </BoundaryIntermediateEvents>
          <formMapping xmi:type="process:FormMapping" xmi:id="_3P_oYKc1EfGSnoVaS4_jWA" type="NONE">
            <targetForm xmi:type="expression:Expression" xmi:id="_zuADZLLdEfGMcrvc5IFQ8w" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_3P_BWKc1EfGSnoVaS4_jWA">
            <inputs xmi:type="process:ContractInput" xmi:id="_7XYdkLwHEfGwTswz-VTf0w" name="input1" type="BOOLEAN">
              <mapping xmi:type="process:ContractInputMapping" xmi:id="_7XYdkbwHEfGwTswz-VTf0w"/>
            </inputs>
          </contract>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_3P_oYqc1EfGSnoVaS4_jWA" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_mpLxsKc2EfGSnoVaS4_jWA" documentation="Esta tarea materializa la oferta adjudicada mediante la ejecución de las acciones de ayuda comprometidas." name="Ejecutar y finalizar actividades de ayuda" outgoing="_kiQFsKytEfGhNt0l83QQlQ" incoming="_gUoOsKytEfGhNt0l83QQlQ" actor="_mnwDgKfUEfG0OL1MHS4NJA" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_mpLxsqc2EfGSnoVaS4_jWA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_mpLxsac2EfGSnoVaS4_jWA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_mpLxs6c2EfGSnoVaS4_jWA" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_mpLxtKc2EfGSnoVaS4_jWA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_mpLxtac2EfGSnoVaS4_jWA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_mpLxtqc2EfGSnoVaS4_jWA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_mpLxuKc2EfGSnoVaS4_jWA" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_mpLxt6c2EfGSnoVaS4_jWA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_mpLxuqc2EfGSnoVaS4_jWA" type="NONE">
            <targetForm xmi:type="expression:Expression" xmi:id="_zuADZbLdEfGMcrvc5IFQ8w" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_mpLxuac2EfGSnoVaS4_jWA"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_mpLxvKc2EfGSnoVaS4_jWA" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
      </elements>
      <elements xmi:type="process:Lane" xmi:id="_IIpXkKpXEfGoZ6gUKq0Gdw" name="Sistema Nacional de Recursos">
        <elements xmi:type="process:ServiceTask" xmi:id="_TGZekKpXEfGoZ6gUKq0Gdw" documentation="Evalúa las ofertas recibidas y retorna perfiles de competencia o habilitación asociados a cada una, evitando rechazos binarios y facilitando su posterior asignación." name="Validar Ofertas " outgoing="_-f8zQKysEfGhNt0l83QQlQ" incoming="_ps1gULu4EfGcCZX-Fsupjg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_TGZekapXEfGoZ6gUKq0Gdw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_TGZekqpXEfGoZ6gUKq0Gdw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_TGZek6pXEfGoZ6gUKq0Gdw" name="" content="" returnTypeFixed="true"/>
          <data xmi:type="process:Data" xmi:id="_3tkQcLzGEfGA-d5gIcTVlw" name="jwt_token_backend" dataType="_qnkYkKKMEfGM4bfaUYLK2A">
            <defaultValue xmi:type="expression:Expression" xmi:id="_3tkQcbzGEfGA-d5gIcTVlw" content=""/>
          </data>
          <connectors xmi:type="process:Connector" xmi:id="_icmgwLxkEfGwgca0dziNHw" name="Login API Backend" definitionId="rest-post" event="ON_ENTER" definitionVersion="1.5.0">
            <configuration xmi:type="connectorconfiguration:ConnectorConfiguration" xmi:id="_icmgwbxkEfGwgca0dziNHw" definitionId="rest-post" version="1.5.0" modelVersion="9">
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_icmgwrxkEfGwgca0dziNHw" key="url">
                <expression xmi:type="expression:Expression" xmi:id="_icmgw7xkEfGwgca0dziNHw" name="http://localhost:3000/api/rescue/auth/login" content="http://localhost:3000/api/rescue/auth/login" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_icmgxLxkEfGwgca0dziNHw" key="contentType">
                <expression xmi:type="expression:Expression" xmi:id="_icmgxbxkEfGwgca0dziNHw" name="application/json" content="application/json" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_icmgxrxkEfGwgca0dziNHw" key="charset">
                <expression xmi:type="expression:Expression" xmi:id="_icmgx7xkEfGwgca0dziNHw" name="UTF-8" content="UTF-8" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_icmgyLxkEfGwgca0dziNHw" key="urlCookies">
                <expression xmi:type="expression:TableExpression" xmi:id="_icmgybxkEfGwgca0dziNHw"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_icmgyrxkEfGwgca0dziNHw" key="urlHeaders">
                <expression xmi:type="expression:TableExpression" xmi:id="_icmgy7xkEfGwgca0dziNHw"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_icmgzLxkEfGwgca0dziNHw" key="add_bonita_context_headers">
                <expression xmi:type="expression:Expression" xmi:id="_icmgzbxkEfGwgca0dziNHw" name="false" content="false" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_icmgzrxkEfGwgca0dziNHw" key="bonita_activity_instance_id_header">
                <expression xmi:type="expression:Expression" xmi:id="_icmgz7xkEfGwgca0dziNHw" name="X-Bonita-Activity-Instance-Id" content="X-Bonita-Activity-Instance-Id" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_icmg0LxkEfGwgca0dziNHw" key="bonita_process_instance_id_header">
                <expression xmi:type="expression:Expression" xmi:id="_icmg0bxkEfGwgca0dziNHw" name="X-Bonita-Process-Instance-Id" content="X-Bonita-Process-Instance-Id" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_icmg0rxkEfGwgca0dziNHw" key="bonita_root_process_instance_id_header">
                <expression xmi:type="expression:Expression" xmi:id="_icmg07xkEfGwgca0dziNHw" name="X-Bonita-Root-Process-Instance-Id" content="X-Bonita-Root-Process-Instance-Id" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_icmg1LxkEfGwgca0dziNHw" key="bonita_process_definition_id_header">
                <expression xmi:type="expression:Expression" xmi:id="_icmg1bxkEfGwgca0dziNHw" name="X-Bonita-Process-Definition-Id" content="X-Bonita-Process-Definition-Id" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_icmg1rxkEfGwgca0dziNHw" key="bonita_task_assignee_id_header">
                <expression xmi:type="expression:Expression" xmi:id="_icmg17xkEfGwgca0dziNHw" name="X-Bonita-Task-Assignee-Id" content="X-Bonita-Task-Assignee-Id" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_icmg2LxkEfGwgca0dziNHw" key="body">
                <expression xmi:type="expression:Expression" xmi:id="_icmg2bxkEfGwgca0dziNHw" name="&lt;pattern-expression>" content="{&#xD;&#xA;&#x9;&quot;username&quot;: &quot;bonita.bpm&quot;,&#xD;&#xA;&#x9;&quot;password&quot;: &quot;bpm&quot; &#xD;&#xA;}" type="TYPE_PATTERN" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_icmg2rxkEfGwgca0dziNHw" key="do_not_follow_redirect">
                <expression xmi:type="expression:Expression" xmi:id="_icmg27xkEfGwgca0dziNHw" name="false" content="false" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_icmg3LxkEfGwgca0dziNHw" key="ignore_body">
                <expression xmi:type="expression:Expression" xmi:id="_icmg3bxkEfGwgca0dziNHw" name="false" content="false" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_icmg3rxkEfGwgca0dziNHw" key="fail_on_http_4xx">
                <expression xmi:type="expression:Expression" xmi:id="_icmg37xkEfGwgca0dziNHw" name="false" content="false" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_icmg4LxkEfGwgca0dziNHw" key="fail_on_http_5xx">
                <expression xmi:type="expression:Expression" xmi:id="_icmg4bxkEfGwgca0dziNHw" name="false" content="false" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_icmg4rxkEfGwgca0dziNHw" key="failure_exception_codes">
                <expression xmi:type="expression:TableExpression" xmi:id="_icmg47xkEfGwgca0dziNHw"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_icmg5LxkEfGwgca0dziNHw" key="retry_on_http_5xx">
                <expression xmi:type="expression:Expression" xmi:id="_icmg5bxkEfGwgca0dziNHw" name="false" content="false" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_icmg5rxkEfGwgca0dziNHw" key="retry_additional_codes">
                <expression xmi:type="expression:TableExpression" xmi:id="_icmg57xkEfGwgca0dziNHw"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_icmg6LxkEfGwgca0dziNHw" key="max_body_content_printed">
                <expression xmi:type="expression:Expression" xmi:id="_icmg6bxkEfGwgca0dziNHw" name="1000" content="1000" returnType="java.lang.Integer" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_icmg6rxkEfGwgca0dziNHw" key="sensitive_headers_printed">
                <expression xmi:type="expression:Expression" xmi:id="_icmg67xkEfGwgca0dziNHw" name="false" content="false" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_icmg7LxkEfGwgca0dziNHw" key="TLS">
                <expression xmi:type="expression:Expression" xmi:id="_icmg7bxkEfGwgca0dziNHw" name="false" content="false" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_icmg7rxkEfGwgca0dziNHw" key="hostname_verifier">
                <expression xmi:type="expression:Expression" xmi:id="_icmg77xkEfGwgca0dziNHw" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_icmg8LxkEfGwgca0dziNHw" key="trust_store_file">
                <expression xmi:type="expression:Expression" xmi:id="_icmg8bxkEfGwgca0dziNHw" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_icmg8rxkEfGwgca0dziNHw" key="trust_store_password">
                <expression xmi:type="expression:Expression" xmi:id="_icmg87xkEfGwgca0dziNHw" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_icmg9LxkEfGwgca0dziNHw" key="key_store_file">
                <expression xmi:type="expression:Expression" xmi:id="_icmg9bxkEfGwgca0dziNHw" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_icmg9rxkEfGwgca0dziNHw" key="key_store_password">
                <expression xmi:type="expression:Expression" xmi:id="_icmg97xkEfGwgca0dziNHw" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_icmg-LxkEfGwgca0dziNHw" key="auth_type">
                <expression xmi:type="expression:Expression" xmi:id="_icmg-bxkEfGwgca0dziNHw" name="NONE" content="NONE" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_icmg-rxkEfGwgca0dziNHw" key="auth_username">
                <expression xmi:type="expression:Expression" xmi:id="_icmg-7xkEfGwgca0dziNHw" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_icmg_LxkEfGwgca0dziNHw" key="auth_password">
                <expression xmi:type="expression:Expression" xmi:id="_icmg_bxkEfGwgca0dziNHw" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_icmg_rxkEfGwgca0dziNHw" key="auth_host">
                <expression xmi:type="expression:Expression" xmi:id="_icmg_7xkEfGwgca0dziNHw" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_icmhALxkEfGwgca0dziNHw" key="auth_port">
                <expression xmi:type="expression:Expression" xmi:id="_icmhAbxkEfGwgca0dziNHw" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_icmhArxkEfGwgca0dziNHw" key="auth_realm">
                <expression xmi:type="expression:Expression" xmi:id="_icmhA7xkEfGwgca0dziNHw" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_icmhBLxkEfGwgca0dziNHw" key="auth_preemptive">
                <expression xmi:type="expression:Expression" xmi:id="_icmhBbxkEfGwgca0dziNHw" name="true" content="true" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_icmhBrxkEfGwgca0dziNHw" key="oauth2_token_endpoint">
                <expression xmi:type="expression:Expression" xmi:id="_icmhB7xkEfGwgca0dziNHw" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_icmhCLxkEfGwgca0dziNHw" key="oauth2_client_id">
                <expression xmi:type="expression:Expression" xmi:id="_icmhCbxkEfGwgca0dziNHw" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_icmhCrxkEfGwgca0dziNHw" key="oauth2_client_secret">
                <expression xmi:type="expression:Expression" xmi:id="_icmhC7xkEfGwgca0dziNHw" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_icmhDLxkEfGwgca0dziNHw" key="oauth2_scope">
                <expression xmi:type="expression:Expression" xmi:id="_icmhDbxkEfGwgca0dziNHw" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_icmhDrxkEfGwgca0dziNHw" key="oauth2_token">
                <expression xmi:type="expression:Expression" xmi:id="_icmhD7xkEfGwgca0dziNHw" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_icmhELxkEfGwgca0dziNHw" key="oauth2_code">
                <expression xmi:type="expression:Expression" xmi:id="_icmhEbxkEfGwgca0dziNHw" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_icmhErxkEfGwgca0dziNHw" key="oauth2_code_verifier">
                <expression xmi:type="expression:Expression" xmi:id="_icmhE7xkEfGwgca0dziNHw" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_icmhFLxkEfGwgca0dziNHw" key="oauth2_redirect_uri">
                <expression xmi:type="expression:Expression" xmi:id="_icmhFbxkEfGwgca0dziNHw" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_icmhFrxkEfGwgca0dziNHw" key="proxy_protocol">
                <expression xmi:type="expression:Expression" xmi:id="_icmhF7xkEfGwgca0dziNHw" name="HTTP" content="HTTP" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_icmhGLxkEfGwgca0dziNHw" key="proxy_host">
                <expression xmi:type="expression:Expression" xmi:id="_icmhGbxkEfGwgca0dziNHw" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_icmhGrxkEfGwgca0dziNHw" key="proxy_port">
                <expression xmi:type="expression:Expression" xmi:id="_icmhG7xkEfGwgca0dziNHw" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_icmhHLxkEfGwgca0dziNHw" key="proxy_username">
                <expression xmi:type="expression:Expression" xmi:id="_icmhHbxkEfGwgca0dziNHw" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_icmhHrxkEfGwgca0dziNHw" key="proxy_password">
                <expression xmi:type="expression:Expression" xmi:id="_icmhH7xkEfGwgca0dziNHw" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_icmhILxkEfGwgca0dziNHw" key="automatic_proxy_resolution">
                <expression xmi:type="expression:Expression" xmi:id="_icmhIbxkEfGwgca0dziNHw" name="false" content="false" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_icmhIrxkEfGwgca0dziNHw" key="socket_timeout_ms">
                <expression xmi:type="expression:Expression" xmi:id="_icmhI7xkEfGwgca0dziNHw" name="60000" content="60000" returnType="java.lang.Integer" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_icmhJLxkEfGwgca0dziNHw" key="connection_timeout_ms">
                <expression xmi:type="expression:Expression" xmi:id="_icmhJbxkEfGwgca0dziNHw" name="60000" content="60000" returnType="java.lang.Integer" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_icmhJrxkEfGwgca0dziNHw" key="trust_strategy">
                <expression xmi:type="expression:Expression" xmi:id="_icmhJ7xkEfGwgca0dziNHw" name="DEFAULT" content="DEFAULT" returnTypeFixed="true"/>
              </parameters>
            </configuration>
            <outputs xmi:type="expression:Operation" xmi:id="_icmhKLxkEfGwgca0dziNHw">
              <leftOperand xmi:type="expression:Expression" xmi:id="_icmhKbxkEfGwgca0dziNHw" name="jwt_token_backend" content="jwt_token_backend" type="TYPE_VARIABLE">
                <referencedElements xmi:type="process:Data" xmi:id="_-oxIALzGEfGA-d5gIcTVlw" name="jwt_token_backend" dataType="_qnkYkKKMEfGM4bfaUYLK2A"/>
              </leftOperand>
              <rightOperand xmi:type="expression:Expression" xmi:id="_icmhK7xkEfGwgca0dziNHw" name="getJWToken()" content="import groovy.json.JsonSlurper&#xD;&#xA;&#xD;&#xA;// 1. Obtener la respuesta en texto plano que devuelve el conector REST&#xD;&#xA;if (bodyAsString == null || bodyAsString.trim().isEmpty()) {&#xD;&#xA;&#x9;return false // o un valor por defecto seguro según tu tipo de variable&#xD;&#xA;}&#xD;&#xA;&#xD;&#xA;// 2. Parsear el JSON&#xD;&#xA;def json = new JsonSlurper().parseText(bodyAsString)&#xD;&#xA;&#xD;&#xA;// 3. Extraer el campo específico de la estructura JSON&#xD;&#xA;// Supongamos que tu API responde: { &quot;status&quot;: &quot;OK&quot;, &quot;data&quot;: { &quot;coberturaCompleta&quot;: true } }&#xD;&#xA;return &quot;Bearer &quot; + json.access_token" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
                <referencedElements xmi:type="definition:Output" xmi:id="_GTbvQLxnEfGwgca0dziNHw" name="bodyAsString" type="java.lang.String"/>
              </rightOperand>
              <operator xmi:type="expression:Operator" xmi:id="_icmhLLxkEfGwgca0dziNHw" type="ASSIGNMENT"/>
            </outputs>
          </connectors>
          <connectors xmi:type="process:Connector" xmi:id="_ghJh4Lx-EfGhkoDHbXfiYw" name="Notificar Timeout" definitionId="rest-post" event="ON_ENTER" definitionVersion="1.5.0">
            <configuration xmi:type="connectorconfiguration:ConnectorConfiguration" xmi:id="_ghKI8Lx-EfGhkoDHbXfiYw" definitionId="rest-post" version="1.5.0" modelVersion="9">
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_ghKI8bx-EfGhkoDHbXfiYw" key="url">
                <expression xmi:type="expression:Expression" xmi:id="_ghKI8rx-EfGhkoDHbXfiYw" name="http://localhost:3000/api/rescue/emergencias/notificar_timeout" content="http://localhost:3000/api/rescue/emergencias/notificar_timeout" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_ghKI9Lx-EfGhkoDHbXfiYw" key="contentType">
                <expression xmi:type="expression:Expression" xmi:id="_ghKI9bx-EfGhkoDHbXfiYw" name="application/json" content="application/json" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_ghKI9rx-EfGhkoDHbXfiYw" key="charset">
                <expression xmi:type="expression:Expression" xmi:id="_ghKI97x-EfGhkoDHbXfiYw" name="UTF-8" content="UTF-8" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_ghKI-Lx-EfGhkoDHbXfiYw" key="urlCookies">
                <expression xmi:type="expression:TableExpression" xmi:id="_ghKI-bx-EfGhkoDHbXfiYw"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_ghKI-rx-EfGhkoDHbXfiYw" key="urlHeaders">
                <expression xmi:type="expression:TableExpression" xmi:id="_ghKI-7x-EfGhkoDHbXfiYw">
                  <expressions xmi:type="expression:ListExpression" xmi:id="_Bwt58LzTEfGcd5EiBrwqrQ">
                    <expressions xmi:type="expression:Expression" xmi:id="_Bwt58bzTEfGcd5EiBrwqrQ" name="Authorization" content="Authorization"/>
                    <expressions xmi:type="expression:Expression" xmi:id="_Bwt58rzTEfGcd5EiBrwqrQ" name="newScript()" content="return jwt_token_backend" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
                      <referencedElements xmi:type="process:Data" xmi:id="_Bwt587zTEfGcd5EiBrwqrQ" name="jwt_token_backend" dataType="_qnkYkKKMEfGM4bfaUYLK2A"/>
                    </expressions>
                  </expressions>
                </expression>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_ghKJALx-EfGhkoDHbXfiYw" key="add_bonita_context_headers">
                <expression xmi:type="expression:Expression" xmi:id="_ghKJAbx-EfGhkoDHbXfiYw" name="false" content="false" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_ghKJArx-EfGhkoDHbXfiYw" key="bonita_activity_instance_id_header">
                <expression xmi:type="expression:Expression" xmi:id="_ghKJA7x-EfGhkoDHbXfiYw" name="X-Bonita-Activity-Instance-Id" content="X-Bonita-Activity-Instance-Id" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_ghKJBLx-EfGhkoDHbXfiYw" key="bonita_process_instance_id_header">
                <expression xmi:type="expression:Expression" xmi:id="_ghKJBbx-EfGhkoDHbXfiYw" name="X-Bonita-Process-Instance-Id" content="X-Bonita-Process-Instance-Id" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_ghKJBrx-EfGhkoDHbXfiYw" key="bonita_root_process_instance_id_header">
                <expression xmi:type="expression:Expression" xmi:id="_ghKJB7x-EfGhkoDHbXfiYw" name="X-Bonita-Root-Process-Instance-Id" content="X-Bonita-Root-Process-Instance-Id" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_ghKJCLx-EfGhkoDHbXfiYw" key="bonita_process_definition_id_header">
                <expression xmi:type="expression:Expression" xmi:id="_ghKJCbx-EfGhkoDHbXfiYw" name="X-Bonita-Process-Definition-Id" content="X-Bonita-Process-Definition-Id" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_ghKJCrx-EfGhkoDHbXfiYw" key="bonita_task_assignee_id_header">
                <expression xmi:type="expression:Expression" xmi:id="_ghKJC7x-EfGhkoDHbXfiYw" name="X-Bonita-Task-Assignee-Id" content="X-Bonita-Task-Assignee-Id" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_ghKJDLx-EfGhkoDHbXfiYw" key="body">
                <expression xmi:type="expression:Expression" xmi:id="_ghKJDbx-EfGhkoDHbXfiYw" name="body()" content="import groovy.json.JsonOutput&#xD;&#xA;&#xD;&#xA;return JsonOutput.toJson([&#xD;&#xA;&#x9;case_id: processInstanceId.toString()&#xD;&#xA;])" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnTypeFixed="true">
                  <referencedElements xmi:type="expression:Expression" xmi:id="_BwuhALzTEfGcd5EiBrwqrQ" name="processInstanceId" content="processInstanceId" type="TYPE_ENGINE_CONSTANT" returnType="java.lang.Long"/>
                </expression>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_ghKJDrx-EfGhkoDHbXfiYw" key="do_not_follow_redirect">
                <expression xmi:type="expression:Expression" xmi:id="_ghKJD7x-EfGhkoDHbXfiYw" name="false" content="false" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_ghKJELx-EfGhkoDHbXfiYw" key="ignore_body">
                <expression xmi:type="expression:Expression" xmi:id="_ghKJEbx-EfGhkoDHbXfiYw" name="false" content="false" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_ghKJErx-EfGhkoDHbXfiYw" key="fail_on_http_4xx">
                <expression xmi:type="expression:Expression" xmi:id="_ghKJE7x-EfGhkoDHbXfiYw" name="false" content="false" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_ghKJFLx-EfGhkoDHbXfiYw" key="fail_on_http_5xx">
                <expression xmi:type="expression:Expression" xmi:id="_ghKJFbx-EfGhkoDHbXfiYw" name="false" content="false" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_ghKJFrx-EfGhkoDHbXfiYw" key="failure_exception_codes">
                <expression xmi:type="expression:TableExpression" xmi:id="_ghKJF7x-EfGhkoDHbXfiYw"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_ghKJGLx-EfGhkoDHbXfiYw" key="retry_on_http_5xx">
                <expression xmi:type="expression:Expression" xmi:id="_ghKJGbx-EfGhkoDHbXfiYw" name="false" content="false" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_ghKJGrx-EfGhkoDHbXfiYw" key="retry_additional_codes">
                <expression xmi:type="expression:TableExpression" xmi:id="_ghKJG7x-EfGhkoDHbXfiYw"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_ghKJHLx-EfGhkoDHbXfiYw" key="max_body_content_printed">
                <expression xmi:type="expression:Expression" xmi:id="_ghKJHbx-EfGhkoDHbXfiYw" name="1000" content="1000" returnType="java.lang.Integer" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_ghKJHrx-EfGhkoDHbXfiYw" key="sensitive_headers_printed">
                <expression xmi:type="expression:Expression" xmi:id="_ghKJH7x-EfGhkoDHbXfiYw" name="false" content="false" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_ghKJILx-EfGhkoDHbXfiYw" key="TLS">
                <expression xmi:type="expression:Expression" xmi:id="_ghKJIbx-EfGhkoDHbXfiYw" name="true" content="true" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_ghKJIrx-EfGhkoDHbXfiYw" key="hostname_verifier">
                <expression xmi:type="expression:Expression" xmi:id="_ghKJI7x-EfGhkoDHbXfiYw" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_ghKJJLx-EfGhkoDHbXfiYw" key="trust_store_file">
                <expression xmi:type="expression:Expression" xmi:id="_ghKJJbx-EfGhkoDHbXfiYw" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_ghKJJrx-EfGhkoDHbXfiYw" key="trust_store_password">
                <expression xmi:type="expression:Expression" xmi:id="_ghKJJ7x-EfGhkoDHbXfiYw" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_ghKJKLx-EfGhkoDHbXfiYw" key="key_store_file">
                <expression xmi:type="expression:Expression" xmi:id="_ghKJKbx-EfGhkoDHbXfiYw" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_ghKJKrx-EfGhkoDHbXfiYw" key="key_store_password">
                <expression xmi:type="expression:Expression" xmi:id="_ghKJK7x-EfGhkoDHbXfiYw" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_ghKJLLx-EfGhkoDHbXfiYw" key="auth_type">
                <expression xmi:type="expression:Expression" xmi:id="_ghKJLbx-EfGhkoDHbXfiYw" name="NONE" content="NONE" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_ghKJLrx-EfGhkoDHbXfiYw" key="auth_username">
                <expression xmi:type="expression:Expression" xmi:id="_ghKJL7x-EfGhkoDHbXfiYw" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_ghKJMLx-EfGhkoDHbXfiYw" key="auth_password">
                <expression xmi:type="expression:Expression" xmi:id="_ghKJMbx-EfGhkoDHbXfiYw" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_ghKJMrx-EfGhkoDHbXfiYw" key="auth_host">
                <expression xmi:type="expression:Expression" xmi:id="_ghKJM7x-EfGhkoDHbXfiYw" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_ghKJNLx-EfGhkoDHbXfiYw" key="auth_port">
                <expression xmi:type="expression:Expression" xmi:id="_ghKJNbx-EfGhkoDHbXfiYw" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_ghKJNrx-EfGhkoDHbXfiYw" key="auth_realm">
                <expression xmi:type="expression:Expression" xmi:id="_ghKJN7x-EfGhkoDHbXfiYw" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_ghKJOLx-EfGhkoDHbXfiYw" key="auth_preemptive">
                <expression xmi:type="expression:Expression" xmi:id="_ghKJObx-EfGhkoDHbXfiYw" name="true" content="true" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_ghKJOrx-EfGhkoDHbXfiYw" key="oauth2_token_endpoint">
                <expression xmi:type="expression:Expression" xmi:id="_ghKJO7x-EfGhkoDHbXfiYw" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_ghKJPLx-EfGhkoDHbXfiYw" key="oauth2_client_id">
                <expression xmi:type="expression:Expression" xmi:id="_ghKJPbx-EfGhkoDHbXfiYw" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_ghKJPrx-EfGhkoDHbXfiYw" key="oauth2_client_secret">
                <expression xmi:type="expression:Expression" xmi:id="_ghKJP7x-EfGhkoDHbXfiYw" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_ghKJQLx-EfGhkoDHbXfiYw" key="oauth2_scope">
                <expression xmi:type="expression:Expression" xmi:id="_ghKJQbx-EfGhkoDHbXfiYw" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_ghKJQrx-EfGhkoDHbXfiYw" key="oauth2_token">
                <expression xmi:type="expression:Expression" xmi:id="_ghKJQ7x-EfGhkoDHbXfiYw" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_ghKJRLx-EfGhkoDHbXfiYw" key="oauth2_code">
                <expression xmi:type="expression:Expression" xmi:id="_ghKJRbx-EfGhkoDHbXfiYw" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_ghKJRrx-EfGhkoDHbXfiYw" key="oauth2_code_verifier">
                <expression xmi:type="expression:Expression" xmi:id="_ghKJR7x-EfGhkoDHbXfiYw" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_ghKJSLx-EfGhkoDHbXfiYw" key="oauth2_redirect_uri">
                <expression xmi:type="expression:Expression" xmi:id="_ghKJSbx-EfGhkoDHbXfiYw" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_ghKJSrx-EfGhkoDHbXfiYw" key="proxy_protocol">
                <expression xmi:type="expression:Expression" xmi:id="_ghKJS7x-EfGhkoDHbXfiYw" name="HTTP" content="HTTP" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_ghKJTLx-EfGhkoDHbXfiYw" key="proxy_host">
                <expression xmi:type="expression:Expression" xmi:id="_ghKJTbx-EfGhkoDHbXfiYw" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_ghKJTrx-EfGhkoDHbXfiYw" key="proxy_port">
                <expression xmi:type="expression:Expression" xmi:id="_ghKJT7x-EfGhkoDHbXfiYw" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_ghKJULx-EfGhkoDHbXfiYw" key="proxy_username">
                <expression xmi:type="expression:Expression" xmi:id="_ghKJUbx-EfGhkoDHbXfiYw" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_ghKJUrx-EfGhkoDHbXfiYw" key="proxy_password">
                <expression xmi:type="expression:Expression" xmi:id="_ghKJU7x-EfGhkoDHbXfiYw" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_ghKJVLx-EfGhkoDHbXfiYw" key="automatic_proxy_resolution">
                <expression xmi:type="expression:Expression" xmi:id="_ghKJVbx-EfGhkoDHbXfiYw" name="false" content="false" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_ghKJVrx-EfGhkoDHbXfiYw" key="socket_timeout_ms">
                <expression xmi:type="expression:Expression" xmi:id="_ghKJV7x-EfGhkoDHbXfiYw" name="60000" content="60000" returnType="java.lang.Integer" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_ghKJWLx-EfGhkoDHbXfiYw" key="connection_timeout_ms">
                <expression xmi:type="expression:Expression" xmi:id="_ghKJWbx-EfGhkoDHbXfiYw" name="60000" content="60000" returnType="java.lang.Integer" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_ghKJWrx-EfGhkoDHbXfiYw" key="trust_strategy">
                <expression xmi:type="expression:Expression" xmi:id="_ghKJW7x-EfGhkoDHbXfiYw" name="DEFAULT" content="DEFAULT" returnTypeFixed="true"/>
              </parameters>
            </configuration>
          </connectors>
          <loopCondition xmi:type="expression:Expression" xmi:id="_TGZelKpXEfGoZ6gUKq0Gdw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_TGZelapXEfGoZ6gUKq0Gdw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_TGZelqpXEfGoZ6gUKq0Gdw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_TGZel6pXEfGoZ6gUKq0Gdw" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_TGZemKpXEfGoZ6gUKq0Gdw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_XRJgYKpaEfGoZ6gUKq0Gdw" documentation="Esta tarea registra y bloquea los recursos comprometidos por la ONG para evitar su utilización simultánea en otras emergencias." name="Reservar  compromiso de recursos" outgoing="_fauyQKytEfGhNt0l83QQlQ" incoming="_O61jMK1vEfGkRvrEd11-kw">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_XRJgYqpaEfGoZ6gUKq0Gdw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_XRJgYapaEfGoZ6gUKq0Gdw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_XRJgY6paEfGoZ6gUKq0Gdw" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_XRJgZKpaEfGoZ6gUKq0Gdw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_XRJgZapaEfGoZ6gUKq0Gdw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_XRJgZqpaEfGoZ6gUKq0Gdw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_XRJgaKpaEfGoZ6gUKq0Gdw" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_XRJgZ6paEfGoZ6gUKq0Gdw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_w4pXoKpdEfGoZ6gUKq0Gdw" documentation="Esta tarea actualiza el estado de los proyectos o actividades asociadas a la emergencia, registrándolos como finalizados una vez completadas las acciones de asistencia y libera los recursos " name="Marcar proyectos como finalizado y liberar recursos" outgoing="_dV10MK1vEfGkRvrEd11-kw" incoming="_kiQFsKytEfGhNt0l83QQlQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_w4p-sapdEfGoZ6gUKq0Gdw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_w4p-sKpdEfGoZ6gUKq0Gdw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_w4p-sqpdEfGoZ6gUKq0Gdw" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_w4p-s6pdEfGoZ6gUKq0Gdw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_w4p-tKpdEfGoZ6gUKq0Gdw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_w4p-tapdEfGoZ6gUKq0Gdw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_w4p-t6pdEfGoZ6gUKq0Gdw" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_w4p-tqpdEfGoZ6gUKq0Gdw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndEvent" xmi:id="_Q6eVYKpeEfGoZ6gUKq0Gdw" name="Fin de emergencia" incoming="_dV10MK1vEfGkRvrEd11-kw">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_Q6e8capeEfGoZ6gUKq0Gdw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_Q6e8cKpeEfGoZ6gUKq0Gdw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_Q6e8cqpeEfGoZ6gUKq0Gdw" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_4FctoKyvEfGhNt0l83QQlQ" name="¿La cobertura es suficiente?" outgoing="_UaVKcKyuEfGhNt0l83QQlQ _Wwiz4KyuEfGhNt0l83QQlQ" incoming="_-f8zQKysEfGhNt0l83QQlQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_-f7lIaysEfGhNt0l83QQlQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_-f7lIKysEfGhNt0l83QQlQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_-f7lIqysEfGhNt0l83QQlQ" name="" content="" returnTypeFixed="true"/>
        </elements>
      </elements>
      <data xmi:type="process:BusinessObjectData" xmi:id="_q4h0ULLZEfGMcrvc5IFQ8w" name="emergencia" dataType="_qnkYk6KMEfGM4bfaUYLK2A" className="ar.com.rescuesync.model.Emergencia">
        <defaultValue xmi:type="expression:Expression" xmi:id="_q4h0UbLZEfGMcrvc5IFQ8w" name="" content="" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Object"/>
      </data>
      <data xmi:type="process:Data" xmi:id="_Y7zmYLuoEfGcCZX-Fsupjg" documentation="Tiempo máximo de espera, expresado en milisegundos, antes de que la tarea finalice automáticamente o continúe por el flujo definido en el temporizador." name="ventana_tiempo_ms" dataType="_qnkYjqKMEfGM4bfaUYLK2A">
        <defaultValue xmi:type="expression:Expression" xmi:id="_Y7zmYbuoEfGcCZX-Fsupjg" name="10000" content="10000" returnType="java.lang.Long"/>
      </data>
      <formMapping xmi:type="process:FormMapping" xmi:id="_qnkYc6KMEfGM4bfaUYLK2A" type="NONE">
        <targetForm xmi:type="expression:Expression" xmi:id="_zuADZrLdEfGMcrvc5IFQ8w" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </formMapping>
      <overviewFormMapping xmi:type="process:FormMapping" xmi:id="_qnkYdaKMEfGM4bfaUYLK2A" type="NONE">
        <targetForm xmi:type="expression:Expression" xmi:id="_xEv3QLLfEfGMcrvc5IFQ8w" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </overviewFormMapping>
      <connections xmi:type="process:SequenceFlow" xmi:id="_qnkYd6KMEfGM4bfaUYLK2A" target="_2A2OEKyuEfGhNt0l83QQlQ" source="_qnkYYqKMEfGM4bfaUYLK2A">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_qnkYeKKMEfGM4bfaUYLK2A"/>
        <condition xmi:type="expression:Expression" xmi:id="_qnkYeaKMEfGM4bfaUYLK2A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_cNlO8KcJEfGqR_1kgwv4Ug" target="_baFVcKcJEfGqR_1kgwv4Ug" source="_jWws0KZ0EfG__aNESQ6L_g">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_cNl2AKcJEfGqR_1kgwv4Ug"/>
        <condition xmi:type="expression:Expression" xmi:id="_cNl2AacJEfGqR_1kgwv4Ug" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_Aa4e0KpQEfGoZ6gUKq0Gdw" target="_GSPaIKpYEfGoZ6gUKq0Gdw" source="_2qWY4KpPEfGoZ6gUKq0Gdw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_Aa5F4KpQEfGoZ6gUKq0Gdw"/>
        <condition xmi:type="expression:Expression" xmi:id="_Aa5F4apQEfGoZ6gUKq0Gdw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_BYtZAKpQEfGoZ6gUKq0Gdw" target="_3PAw8Kc1EfGSnoVaS4_jWA" source="_GSPaIKpYEfGoZ6gUKq0Gdw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_BYtZAapQEfGoZ6gUKq0Gdw"/>
        <condition xmi:type="expression:Expression" xmi:id="_BYtZAqpQEfGoZ6gUKq0Gdw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_MCOh8KysEfGhNt0l83QQlQ" target="_2qWY4KpPEfGoZ6gUKq0Gdw" source="_2A2OEKyuEfGhNt0l83QQlQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_MCOh8aysEfGhNt0l83QQlQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_MCOh8qysEfGhNt0l83QQlQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_-f8zQKysEfGhNt0l83QQlQ" target="_4FctoKyvEfGhNt0l83QQlQ" source="_TGZekKpXEfGoZ6gUKq0Gdw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_-f8zQaysEfGhNt0l83QQlQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_3A5gYqyvEfGhNt0l83QQlQ" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_fauyQKytEfGhNt0l83QQlQ" target="_dJ_bsKpdEfGoZ6gUKq0Gdw" source="_XRJgYKpaEfGoZ6gUKq0Gdw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_favZUKytEfGhNt0l83QQlQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_favZUaytEfGhNt0l83QQlQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_gUoOsKytEfGhNt0l83QQlQ" target="_mpLxsKc2EfGSnoVaS4_jWA" source="_dJ_bsKpdEfGoZ6gUKq0Gdw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_gUoOsaytEfGhNt0l83QQlQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_gUoOsqytEfGhNt0l83QQlQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_kiQFsKytEfGhNt0l83QQlQ" target="_w4pXoKpdEfGoZ6gUKq0Gdw" source="_mpLxsKc2EfGSnoVaS4_jWA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_kiQFsaytEfGhNt0l83QQlQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_kiQFsqytEfGhNt0l83QQlQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_UaVKcKyuEfGhNt0l83QQlQ" name="No" target="_ZIRqgK4SEfG95paOjq0xJQ" source="_4FctoKyvEfGhNt0l83QQlQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_UaVxgKyuEfGhNt0l83QQlQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_3A5gYKyvEfGhNt0l83QQlQ" name="No" content="No" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_Wwiz4KyuEfGhNt0l83QQlQ" name="Si" target="_jWws0KZ0EfG__aNESQ6L_g" source="_4FctoKyvEfGhNt0l83QQlQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_Wwiz4ayuEfGhNt0l83QQlQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_3A5gYayvEfGhNt0l83QQlQ" name="Si" content="Si" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_vE_ocK1tEfGkRvrEd11-kw" target="_GSPaIKpYEfGoZ6gUKq0Gdw" source="_ZIRqgK4SEfG95paOjq0xJQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_vFAPgK1tEfGkRvrEd11-kw"/>
        <condition xmi:type="expression:Expression" xmi:id="_vFAPga1tEfGkRvrEd11-kw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_O61jMK1vEfGkRvrEd11-kw" target="_XRJgYKpaEfGoZ6gUKq0Gdw" source="_baFVcKcJEfGqR_1kgwv4Ug">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_O62xUK1vEfGkRvrEd11-kw"/>
        <condition xmi:type="expression:Expression" xmi:id="_O62xUa1vEfGkRvrEd11-kw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_dV10MK1vEfGkRvrEd11-kw" target="_Q6eVYKpeEfGoZ6gUKq0Gdw" source="_w4pXoKpdEfGoZ6gUKq0Gdw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_dV2bQK1vEfGkRvrEd11-kw"/>
        <condition xmi:type="expression:Expression" xmi:id="_dV3CUK1vEfGkRvrEd11-kw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_ps1gULu4EfGcCZX-Fsupjg" target="_TGZekKpXEfGoZ6gUKq0Gdw" source="_oNl7ILu4EfGcCZX-Fsupjg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_ps2ucLu4EfGcCZX-Fsupjg"/>
        <condition xmi:type="expression:Expression" xmi:id="_ps2ucbu4EfGcCZX-Fsupjg" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <actors xmi:type="process:Actor" xmi:id="_POFZQKZyEfG__aNESQ6L_g" name="Operador Municipal" initiator="true"/>
      <actors xmi:type="process:Actor" xmi:id="_mnwDgKfUEfG0OL1MHS4NJA" name="Representante ONG"/>
      <actors xmi:type="process:Actor" xmi:id="_wvye8KpPEfGoZ6gUKq0Gdw" name="Centro Coordinador"/>
      <contract xmi:type="process:Contract" xmi:id="_qnkYe6KMEfGM4bfaUYLK2A"/>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_qnkYfKKMEfGM4bfaUYLK2A">
        <name xmi:type="expression:Expression" xmi:id="_qnkYfaKMEfGM4bfaUYLK2A" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_qnkYfqKMEfGM4bfaUYLK2A" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_qnkYf6KMEfGM4bfaUYLK2A">
        <name xmi:type="expression:Expression" xmi:id="_qnkYgKKMEfGM4bfaUYLK2A" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_qnkYgaKMEfGM4bfaUYLK2A" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_qnkYgqKMEfGM4bfaUYLK2A">
        <name xmi:type="expression:Expression" xmi:id="_qnkYg6KMEfGM4bfaUYLK2A" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_qnkYhKKMEfGM4bfaUYLK2A" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_qnkYhaKMEfGM4bfaUYLK2A">
        <name xmi:type="expression:Expression" xmi:id="_qnkYhqKMEfGM4bfaUYLK2A" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_qnkYh6KMEfGM4bfaUYLK2A" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_qnkYiKKMEfGM4bfaUYLK2A">
        <name xmi:type="expression:Expression" xmi:id="_qnkYiaKMEfGM4bfaUYLK2A" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_qnkYiqKMEfGM4bfaUYLK2A" content="" returnTypeFixed="true"/>
      </searchIndexes>
    </elements>
    <datatypes xmi:type="process:BooleanType" xmi:id="_qnkYi6KMEfGM4bfaUYLK2A" name="Boolean"/>
    <datatypes xmi:type="process:DateType" xmi:id="_qnkYjKKMEfGM4bfaUYLK2A" name="Date"/>
    <datatypes xmi:type="process:IntegerType" xmi:id="_qnkYjaKMEfGM4bfaUYLK2A" name="Integer"/>
    <datatypes xmi:type="process:LongType" xmi:id="_qnkYjqKMEfGM4bfaUYLK2A" name="Long"/>
    <datatypes xmi:type="process:DoubleType" xmi:id="_qnkYj6KMEfGM4bfaUYLK2A" name="Double"/>
    <datatypes xmi:type="process:StringType" xmi:id="_qnkYkKKMEfGM4bfaUYLK2A" name="Text"/>
    <datatypes xmi:type="process:JavaType" xmi:id="_qnkYkaKMEfGM4bfaUYLK2A" name="Java_object"/>
    <datatypes xmi:type="process:XMLType" xmi:id="_qnkYkqKMEfGM4bfaUYLK2A" name="XML"/>
    <datatypes xmi:type="process:BusinessObjectType" xmi:id="_qnkYk6KMEfGM4bfaUYLK2A" name="Business_Object"/>
  </process:MainProcess>
  <notation:Diagram xmi:id="_qnkYlKKMEfGM4bfaUYLK2A" type="Process" element="_qnjxUKKMEfGM4bfaUYLK2A" name="MyDiagram" measurementUnit="Pixel">
    <children xmi:type="notation:Node" xmi:id="_qnkYlaKMEfGM4bfaUYLK2A" type="2007" element="_qnkYYKKMEfGM4bfaUYLK2A">
      <children xmi:type="notation:DecorationNode" xmi:id="_qnkYlqKMEfGM4bfaUYLK2A" type="5008"/>
      <children xmi:type="notation:DecorationNode" xmi:id="_qnkYl6KMEfGM4bfaUYLK2A" type="7001">
        <children xmi:type="notation:Node" xmi:id="_qnkYmKKMEfGM4bfaUYLK2A" type="3007" element="_qnkYYaKMEfGM4bfaUYLK2A">
          <children xmi:type="notation:DecorationNode" xmi:id="_qnkYmaKMEfGM4bfaUYLK2A" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_qnkYmqKMEfGM4bfaUYLK2A" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_qnkYnqKMEfGM4bfaUYLK2A" type="3002" element="_qnkYYqKMEfGM4bfaUYLK2A" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_qnkYn6KMEfGM4bfaUYLK2A" type="5024">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_qnkYoKKMEfGM4bfaUYLK2A" x="5" y="-56"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_qnkYoaKMEfGM4bfaUYLK2A" x="78" y="46"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_jW1lUKZ0EfG__aNESQ6L_g" type="3005" element="_jWws0KZ0EfG__aNESQ6L_g" fontName="Segoe UI" fontHeight="8" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_jW2MYKZ0EfG__aNESQ6L_g" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_jW1lUaZ0EfG__aNESQ6L_g" x="542" y="65" width="186" height="93"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_baYQYKcJEfGqR_1kgwv4Ug" type="3005" element="_baFVcKcJEfGqR_1kgwv4Ug" fontName="Segoe UI" fontHeight="8" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_baY3cKcJEfGqR_1kgwv4Ug" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_baYQYacJEfGqR_1kgwv4Ug" x="819" y="66" width="182" height="91"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_2A3cMKyuEfGhNt0l83QQlQ" type="3005" element="_2A2OEKyuEfGhNt0l83QQlQ" fontName="Segoe UI" fontHeight="8" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_2A3cMqyuEfGhNt0l83QQlQ" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_2A3cMayuEfGhNt0l83QQlQ" x="55" y="171" width="189" height="94"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_qnkYoqKMEfGM4bfaUYLK2A"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_qnkYo6KMEfGM4bfaUYLK2A" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_qnkYpKKMEfGM4bfaUYLK2A"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_qnkYpaKMEfGM4bfaUYLK2A"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_qnkYpqKMEfGM4bfaUYLK2A" x="58" y="10" width="1287" height="463"/>
        </children>
        <children xmi:type="notation:Node" xmi:id="_IFhnYKLeEfG0-Lqmhfo29w" type="3007" element="_IFdV8KLeEfG0-Lqmhfo29w">
          <children xmi:type="notation:DecorationNode" xmi:id="_IFiOcKLeEfG0-Lqmhfo29w" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_IFiOcaLeEfG0-Lqmhfo29w" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_2qWY7apPEfGoZ6gUKq0Gdw" type="3005" element="_2qWY4KpPEfGoZ6gUKq0Gdw" fontName="Segoe UI" fontHeight="8" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_2qWY7qpPEfGoZ6gUKq0Gdw" type="5005" element="_2qWY4KpPEfGoZ6gUKq0Gdw"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_2qWY76pPEfGoZ6gUKq0Gdw" x="45" y="58" width="181" height="90"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_GSQBMKpYEfGoZ6gUKq0Gdw" type="3027" element="_GSPaIKpYEfGoZ6gUKq0Gdw" fontName="Segoe UI" fontHeight="8" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_GSQBMqpYEfGoZ6gUKq0Gdw" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_GSQBMapYEfGoZ6gUKq0Gdw" x="46" y="220" width="180" height="88"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_dKB38KpdEfGoZ6gUKq0Gdw" type="3027" element="_dJ_bsKpdEfGoZ6gUKq0Gdw" fontName="Segoe UI" fontHeight="8" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_dKB38apdEfGoZ6gUKq0Gdw" type="5017" element="_dJ_bsKpdEfGoZ6gUKq0Gdw"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_dKB38qpdEfGoZ6gUKq0Gdw" x="1009" y="220" width="212" height="106"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_ZIwLoK4SEfG95paOjq0xJQ" type="3005" element="_ZIRqgK4SEfG95paOjq0xJQ" fontName="Ubuntu Sans" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_ZIxZwK4SEfG95paOjq0xJQ" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_ZIwLoa4SEfG95paOjq0xJQ" x="384" y="214" width="191" height="95"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_IFhnYaLeEfG0-Lqmhfo29w"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_IFhnYqLeEfG0-Lqmhfo29w" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_IFhnY6LeEfG0-Lqmhfo29w"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_IFiOcqLeEfG0-Lqmhfo29w"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_IFhnZKLeEfG0-Lqmhfo29w" x="50" y="463" width="1295" height="504"/>
        </children>
        <children xmi:type="notation:Node" xmi:id="_VBarsKMCEfGpRZzXDYFkZQ" type="3007" element="_VASqUKMCEfGpRZzXDYFkZQ">
          <children xmi:type="notation:DecorationNode" xmi:id="_VBbSwKMCEfGpRZzXDYFkZQ" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_VBbSwaMCEfGpRZzXDYFkZQ" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_3Q8DkKc1EfGSnoVaS4_jWA" type="3005" element="_3PAw8Kc1EfGSnoVaS4_jWA" fontName="Segoe UI" fontHeight="8" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_3Q8qoKc1EfGSnoVaS4_jWA" type="5005"/>
              <children xmi:type="notation:Shape" xmi:id="_oNnJQLu4EfGcCZX-Fsupjg" type="3043" element="_oNl7ILu4EfGcCZX-Fsupjg" fontName="Segoe UI">
                <children xmi:type="notation:DecorationNode" xmi:id="_oNnwULu4EfGcCZX-Fsupjg" type="5055">
                  <layoutConstraint xmi:type="notation:Location" xmi:id="_oNnwUbu4EfGcCZX-Fsupjg" x="53" y="12"/>
                </children>
                <layoutConstraint xmi:type="notation:Bounds" xmi:id="_oNnJQbu4EfGcCZX-Fsupjg" x="43" y="71"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_3Q8Dkac1EfGSnoVaS4_jWA" x="46" y="105" width="159" height="79"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_mpMYwKc2EfGSnoVaS4_jWA" type="3005" element="_mpLxsKc2EfGSnoVaS4_jWA" fontName="Segoe UI" fontHeight="8" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_mpMYwqc2EfGSnoVaS4_jWA" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_mpMYwac2EfGSnoVaS4_jWA" x="1048" y="162" width="179" height="89"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_VBarsaMCEfGpRZzXDYFkZQ"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_VBarsqMCEfGpRZzXDYFkZQ" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_VBars6MCEfGpRZzXDYFkZQ"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_VBb50KMCEfGpRZzXDYFkZQ"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_VBartKMCEfGpRZzXDYFkZQ" x="33" y="664" width="1287" height="441"/>
        </children>
        <children xmi:type="notation:Node" xmi:id="_IIrMwKpXEfGoZ6gUKq0Gdw" type="3007" element="_IIpXkKpXEfGoZ6gUKq0Gdw">
          <children xmi:type="notation:DecorationNode" xmi:id="_IIrMxapXEfGoZ6gUKq0Gdw" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_IIrMxqpXEfGoZ6gUKq0Gdw" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_TGZemapXEfGoZ6gUKq0Gdw" type="3027" element="_TGZekKpXEfGoZ6gUKq0Gdw" fontName="Segoe UI" fontHeight="8" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_TGZemqpXEfGoZ6gUKq0Gdw" type="5017" element="_TGZekKpXEfGoZ6gUKq0Gdw"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_TGZem6pXEfGoZ6gUKq0Gdw" x="46" y="57" width="189" height="94"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_XRKHcKpaEfGoZ6gUKq0Gdw" type="3027" element="_XRJgYKpaEfGoZ6gUKq0Gdw" fontName="Segoe UI" fontHeight="8" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_XRKHcqpaEfGoZ6gUKq0Gdw" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_XRKHcapaEfGoZ6gUKq0Gdw" x="762" y="57" width="189" height="94"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_w4p-uKpdEfGoZ6gUKq0Gdw" type="3027" element="_w4pXoKpdEfGoZ6gUKq0Gdw" fontName="Segoe UI" fontHeight="8" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_w4qlwKpdEfGoZ6gUKq0Gdw" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_w4p-uapdEfGoZ6gUKq0Gdw" x="1080" y="136" width="152" height="75"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_Q6fjgKpeEfGoZ6gUKq0Gdw" type="3003" element="_Q6eVYKpeEfGoZ6gUKq0Gdw" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_Q6fjgqpeEfGoZ6gUKq0Gdw" type="5025">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_Q6fjg6peEfGoZ6gUKq0Gdw" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Q6fjgapeEfGoZ6gUKq0Gdw" x="1123" y="310"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_4FdUs6yvEfGhNt0l83QQlQ" type="3008" element="_4FctoKyvEfGhNt0l83QQlQ" fontName="Ubuntu Sans">
              <children xmi:type="notation:DecorationNode" xmi:id="_4FdUtayvEfGhNt0l83QQlQ" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_4FdUtqyvEfGhNt0l83QQlQ" y="19"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_4FdUtKyvEfGhNt0l83QQlQ" x="439" y="82" width="43" height="43"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_IIrMwapXEfGoZ6gUKq0Gdw"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_IIrMwqpXEfGoZ6gUKq0Gdw" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_IIrMw6pXEfGoZ6gUKq0Gdw"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_IIrMx6pXEfGoZ6gUKq0Gdw"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_IIrMxKpXEfGoZ6gUKq0Gdw" x="50" y="1408" width="1295" height="400"/>
        </children>
      </children>
      <styles xmi:type="notation:DescriptionStyle" xmi:id="_qnkYp6KMEfGM4bfaUYLK2A"/>
      <styles xmi:type="notation:FontStyle" xmi:id="_qnkYqKKMEfGM4bfaUYLK2A" fontName="Segoe UI"/>
      <styles xmi:type="notation:LineStyle" xmi:id="_qnkYqaKMEfGM4bfaUYLK2A"/>
      <styles xmi:type="notation:FillStyle" xmi:id="_qnkYqqKMEfGM4bfaUYLK2A"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_qnkYq6KMEfGM4bfaUYLK2A" width="1320" height="250"/>
    </children>
    <styles xmi:type="notation:DiagramStyle" xmi:id="_qnkYrKKMEfGM4bfaUYLK2A"/>
    <edges xmi:type="notation:Connector" xmi:id="_qnkYraKMEfGM4bfaUYLK2A" type="4001" element="_qnkYd6KMEfGM4bfaUYLK2A" source="_qnkYnqKMEfGM4bfaUYLK2A" target="_2A3cMKyuEfGhNt0l83QQlQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_qnkYrqKMEfGM4bfaUYLK2A" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_qnkYr6KMEfGM4bfaUYLK2A" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_qnkYsKKMEfGM4bfaUYLK2A" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_qnkYsaKMEfGM4bfaUYLK2A" points="[-1, 14, -57, -143]$[-1, 110, -57, -47]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_cNnEIKcJEfGqR_1kgwv4Ug" type="4001" element="_cNlO8KcJEfGqR_1kgwv4Ug" source="_jW1lUKZ0EfG__aNESQ6L_g" target="_baYQYKcJEfGqR_1kgwv4Ug" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_cNnrMKcJEfGqR_1kgwv4Ug" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_cNnrMacJEfGqR_1kgwv4Ug" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_cNnEIacJEfGqR_1kgwv4Ug" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_cNnEIqcJEfGqR_1kgwv4Ug" points="[0, 12, -114, -8]$[91, 12, -23, -8]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_cNrVkKcJEfGqR_1kgwv4Ug" id="(1.0,0.28125)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_cNrVkacJEfGqR_1kgwv4Ug" id="(0.13,0.5)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_Aa7iIKpQEfGoZ6gUKq0Gdw" type="4001" element="_Aa4e0KpQEfGoZ6gUKq0Gdw" source="_2qWY7apPEfGoZ6gUKq0Gdw" target="_GSQBMKpYEfGoZ6gUKq0Gdw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_Aa8JMKpQEfGoZ6gUKq0Gdw" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_Aa8JMapQEfGoZ6gUKq0Gdw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_Aa7iIapQEfGoZ6gUKq0Gdw" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_Aa7iIqpQEfGoZ6gUKq0Gdw" points="[-129, 60, 33, -113]$[-129, 132, 33, -41]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_AbAaoKpQEfGoZ6gUKq0Gdw" id="(1.0,0.3333333333333333)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_AbAaoapQEfGoZ6gUKq0Gdw" id="(0.10497237569060773,0.4666666666666667)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_BYvOMKpQEfGoZ6gUKq0Gdw" type="4001" element="_BYtZAKpQEfGoZ6gUKq0Gdw" source="_GSQBMKpYEfGoZ6gUKq0Gdw" target="_3Q8DkKc1EfGSnoVaS4_jWA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_BYv1QKpQEfGoZ6gUKq0Gdw" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_BYv1QapQEfGoZ6gUKq0Gdw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_BYvOMapQEfGoZ6gUKq0Gdw" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_BYvOMqpQEfGoZ6gUKq0Gdw" points="[-129, 57, 3, -309]$[-129, 358, 3, -8]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_BYyRgKpQEfGoZ6gUKq0Gdw" id="(1.0,0.35555555555555557)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_BYyRgapQEfGoZ6gUKq0Gdw" id="(0.3018867924528302,0.10126582278481013)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_MCPJAKysEfGhNt0l83QQlQ" type="4001" element="_MCOh8KysEfGhNt0l83QQlQ" source="_2A3cMKyuEfGhNt0l83QQlQ" target="_2qWY7apPEfGoZ6gUKq0Gdw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_MCPwEKysEfGhNt0l83QQlQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_MCPwEaysEfGhNt0l83QQlQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_MCPJAaysEfGhNt0l83QQlQ" fontName="Ubuntu Sans"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_MCPJAqysEfGhNt0l83QQlQ" points="[-147, 60, -38, -301]$[-147, 316, -38, -45]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_MCRlQKysEfGhNt0l83QQlQ" id="(1.0,0.36666666666666664)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_-f8zQ6ysEfGhNt0l83QQlQ" type="4001" element="_-f8zQKysEfGhNt0l83QQlQ" source="_TGZemapXEfGoZ6gUKq0Gdw" target="_4FdUs6yvEfGhNt0l83QQlQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_-f9aUKysEfGhNt0l83QQlQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_-f9aUaysEfGhNt0l83QQlQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_-f8zRKysEfGhNt0l83QQlQ" fontName="Ubuntu Sans"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_-f8zRaysEfGhNt0l83QQlQ" points="[95, -1, -225, 0]$[299, -1, -21, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_fawncKytEfGhNt0l83QQlQ" type="4001" element="_fauyQKytEfGhNt0l83QQlQ" source="_XRKHcKpaEfGoZ6gUKq0Gdw" target="_dKB38KpdEfGoZ6gUKq0Gdw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_faxOgKytEfGhNt0l83QQlQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_faxOgaytEfGhNt0l83QQlQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_fawncaytEfGhNt0l83QQlQ" fontName="Ubuntu Sans"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_fawncqytEfGhNt0l83QQlQ" points="[0, 0, -105, 750]$[39, 0, -66, 750]$[39, -759, -66, -9]$[58, -759, -47, -9]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_fazqwKytEfGhNt0l83QQlQ" id="(1.0,0.3191489361702128)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_fazqwaytEfGhNt0l83QQlQ" id="(0.22633744855967078,0.5916666666666667)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_gUo1wKytEfGhNt0l83QQlQ" type="4001" element="_gUoOsKytEfGhNt0l83QQlQ" source="_dKB38KpdEfGoZ6gUKq0Gdw" target="_mpMYwKc2EfGSnoVaS4_jWA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_gUpc0KytEfGhNt0l83QQlQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_gUpc0aytEfGhNt0l83QQlQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_gUo1waytEfGhNt0l83QQlQ" fontName="Ubuntu Sans"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_gUo1wqytEfGhNt0l83QQlQ" points="[-76, 81, 8, -384]$[-76, 421, 8, -44]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_gUrSAKytEfGhNt0l83QQlQ" id="(1.0,0.24166666666666667)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_kiRT0KytEfGhNt0l83QQlQ" type="4001" element="_kiQFsKytEfGhNt0l83QQlQ" source="_mpMYwKc2EfGSnoVaS4_jWA" target="_w4p-uKpdEfGoZ6gUKq0Gdw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_kiRT06ytEfGhNt0l83QQlQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_kiRT1KytEfGhNt0l83QQlQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_kiRT0aytEfGhNt0l83QQlQ" fontName="Ubuntu Sans"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_kiRT0qytEfGhNt0l83QQlQ" points="[-85, 56, -14, -363]$[-85, 382, -14, -37]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_kiTJAKytEfGhNt0l83QQlQ" id="(1.0,0.3707865168539326)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_UaW_oKyuEfGhNt0l83QQlQ" type="4001" element="_UaVKcKyuEfGhNt0l83QQlQ" source="_4FdUs6yvEfGhNt0l83QQlQ" target="_ZIwLoK4SEfG95paOjq0xJQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_UaXmsKyuEfGhNt0l83QQlQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_UaXmsayuEfGhNt0l83QQlQ" x="-341" y="-11"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_UaW_oayuEfGhNt0l83QQlQ" fontName="Ubuntu Sans"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_UaW_oqyuEfGhNt0l83QQlQ" points="[-24, -26, -57, 735]$[-24, -746, -57, 15]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_UaZb4KyuEfGhNt0l83QQlQ" id="(1.0,0.6511627906976745)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_UaZb4ayuEfGhNt0l83QQlQ" id="(0.6858638743455497,0.8421052631578947)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_WwyEcKyuEfGhNt0l83QQlQ" type="4001" element="_Wwiz4KyuEfGhNt0l83QQlQ" source="_4FdUs6yvEfGhNt0l83QQlQ" target="_jW1lUKZ0EfG__aNESQ6L_g" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_WwyrgKyuEfGhNt0l83QQlQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_WwyrgayuEfGhNt0l83QQlQ" x="-626" y="-110"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_WwyEcayuEfGhNt0l83QQlQ" fontName="Ubuntu Sans"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_WwyEcqyuEfGhNt0l83QQlQ" points="[0, -12, -153, 1400]$[128, -12, -25, 1400]$[128, -1365, -25, 47]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_WwzSkKyuEfGhNt0l83QQlQ" id="(1.0,0.7674418604651163)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_vFCEsK1tEfGkRvrEd11-kw" type="4001" element="_vE_ocK1tEfGkRvrEd11-kw" source="_ZIwLoK4SEfG95paOjq0xJQ" target="_GSQBMKpYEfGoZ6gUKq0Gdw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_vFDS0K1tEfGkRvrEd11-kw" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_vFDS0a1tEfGkRvrEd11-kw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_vFCEsa1tEfGkRvrEd11-kw" fontName="Ubuntu Sans"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_vFCEsq1tEfGkRvrEd11-kw" points="[-191, 18, 234, -23]$[-255, 18, 170, -23]$[-255, 25, 170, -16]$[-335, 25, 90, -16]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_vFHkQK1tEfGkRvrEd11-kw" id="(1.0,0.3368421052631579)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_O63_cK1vEfGkRvrEd11-kw" type="4001" element="_O61jMK1vEfGkRvrEd11-kw" source="_baYQYKcJEfGqR_1kgwv4Ug" target="_XRKHcKpaEfGoZ6gUKq0Gdw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_O64mgK1vEfGkRvrEd11-kw" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_O64mga1vEfGkRvrEd11-kw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_O63_ca1vEfGkRvrEd11-kw" fontName="Ubuntu Sans"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_O63_cq1vEfGkRvrEd11-kw" points="[-141, 5, -35, -1316]$[-141, 1313, -35, -8]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_O68Q4K1vEfGkRvrEd11-kw" id="(0.9835164835164835,0.945054945054945)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_UsphQLT4EfGhr7Jh7hZxMQ" id="(0.6878306878306878,0.0851063829787234)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_dV4QcK1vEfGkRvrEd11-kw" type="4001" element="_dV10MK1vEfGkRvrEd11-kw" source="_w4p-uKpdEfGoZ6gUKq0Gdw" target="_Q6fjgKpeEfGoZ6gUKq0Gdw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_dV43gK1vEfGkRvrEd11-kw" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_dV43ga1vEfGkRvrEd11-kw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_dV4Qca1vEfGkRvrEd11-kw" fontName="Ubuntu Sans"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_dV4Qcq1vEfGkRvrEd11-kw" points="[-90, 43, 4, -114]$[-90, 142, 4, -15]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_dV9I8K1vEfGkRvrEd11-kw" id="(1.0,0.4266666666666667)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_ps3VgLu4EfGcCZX-Fsupjg" type="4001" element="_ps1gULu4EfGcCZX-Fsupjg" source="_oNnJQLu4EfGcCZX-Fsupjg" target="_TGZemapXEfGoZ6gUKq0Gdw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_ps38kLu4EfGcCZX-Fsupjg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_ps38kbu4EfGcCZX-Fsupjg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_ps3Vgbu4EfGcCZX-Fsupjg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_ps3Vgru4EfGcCZX-Fsupjg" points="[-7, 0, 38, -330]$[-7, 297, 38, -33]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_ps6Y0Lu4EfGcCZX-Fsupjg" id="(1.0,1.0)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_ps6Y0bu4EfGcCZX-Fsupjg" id="(0.12169312169312169,0.35106382978723405)"/>
    </edges>
  </notation:Diagram>
</xmi:XMI>
